# Generated by Django 4.2.6 on 2023-11-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Работники', 'verbose_name_plural': 'Работники'},
        ),
        migrations.AlterField(
            model_name='task',
            name='job',
            field=models.CharField(choices=[('Программист', 'Программист'), ('Слесарь', 'Слесарь'), ('Бухглатер', 'Бухглатер')], default='', max_length=100, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='task',
            name='phone_number',
            field=models.IntegerField(verbose_name='Номер телефона сотрудника'),
        ),
    ]
