# Generated by Django 4.2.6 on 2023-11-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_task_options_alter_task_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='num_staff',
            field=models.CharField(max_length=100, verbose_name='Номер сотрудника'),
        ),
        migrations.AlterField(
            model_name='task',
            name='phone_number',
            field=models.CharField(max_length=100, verbose_name='Номер телефона сотрудника'),
        ),
    ]
